version: '3.8'
services:
  spoolman:
    image: spoolman:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - type: bind
        source: /volume1/docker/Spoolman/data
        target: /home/app/.local/share/spoolman
    ports:
      - 30168:8000
    environment:
      - TZ=Europe/Berlin
      - SPOOLMAN_PRINT_REQUEST_PASSWORD=${SPOOLMAN_PRINT_REQUEST_PASSWORD}
      - SPOOLMAN_PRINT_REQUEST_COOKIE_SECRET=${SPOOLMAN_PRINT_REQUEST_COOKIE_SECRET}
      - SPOOLMAN_PRINT_REQUEST_USER_PASSWORDS=${SPOOLMAN_PRINT_REQUEST_USER_PASSWORDS}
    container_name: Spoolman

  public-print-request:
    build:
      context: ./public-print-request
      dockerfile: Dockerfile
    container_name: Spoolman-Public-Print-Request
    restart: unless-stopped
    depends_on:
      - spoolman
    ports:
      - "30170:80"

  bambulab-ams-filamentstatus:
    depends_on:
      spoolman:
        condition: service_started
    image: ghcr.io/rdiger-36/bambulab-ams-spoolman-filamentstatus:latest
    container_name: Spoolman-AMS-FilamentStatus
    ports:
      - 30169:4000
    environment:
      - SPOOLMAN_ENDPOINT=http://192.168.10.99:30168
      - UPDATE_INTERVAL=120000
      - MODE=manual
    volumes:
      - /volume1/docker/Spoolman/printers:/app/printers
      - /volume1/docker/Spoolman/logs:/app/logs
    restart: unless-stopped
