name: CD

on: workflow_dispatch

jobs:
  deploy:
    name: Deployment
    uses: Canoobi/Workflows/.github/workflows/trigger-deploy.yml@main
    with:
      run_pull_changes: true
      run_stop_compose_containers: true
      run_build_docker_compose_file: true
      run_start_compose_containers: true
      run_restart_non_compose_containers: false
    secrets:
      WORKFLOWS_REPO_TOKEN: ${{ secrets.WORKFLOWS_REPO_TOKEN }}
      REPO_PATH: ${{ secrets.REPO_PATH }}